name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npx playwright install firefox
    - run: npm run test:generate-snapshot-screenshots
    - run: npm run test:generate-pdfs
    - run: npm test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
