name: Update Snapshots
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - run: npm ci
      - run: npx playwright install firefox
      - run: npm run test:generate-pdfs
      - run: rm -rf test/snapshot && mv test/output test/snapshot
      - name: Commit
        run: |
          git config --global user.name 'Decktape bot'
          git config --global user.email 'decktape-bot@users.noreply.github.com'
          git pull
          git add .
          git commit -m "test: update snapshot PDFs"
          git push
